// <auto-generated />
using System;
using AccesoDeDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDeDatos.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20230504155430_ActualizacionClaseFuncionario")]
    partial class ActualizacionClaseFuncionario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelDeCabañas.Entidades.Cabaña", b =>
                {
                    b.Property<int>("NroHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroHabitacion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("cantMax")
                        .HasColumnType("int");

                    b.Property<bool>("estaHabilitada")
                        .HasColumnType("bit");

                    b.Property<bool>("tieneJacuzzi")
                        .HasColumnType("bit");

                    b.HasKey("NroHabitacion");

                    b.HasIndex("TipoNombre");

                    b.ToTable("cabañas");
                });

            modelBuilder.Entity("HotelDeCabañas.Entidades.Funcionario", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("funcionarios");
                });

            modelBuilder.Entity("HotelDeCabañas.Entidades.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabañaNroHabitacion")
                        .HasColumnType("int");

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CabañaNroHabitacion");

                    b.ToTable("mantenimientos");
                });

            modelBuilder.Entity("HotelDeCabañas.Entidades.TipoCabaña", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("costoPorHuesped")
                        .HasColumnType("float");

                    b.HasKey("Nombre");

                    b.ToTable("tipos");
                });

            modelBuilder.Entity("HotelDeCabañas.Entidades.Cabaña", b =>
                {
                    b.HasOne("HotelDeCabañas.Entidades.TipoCabaña", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoNombre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("HotelDeCabañas.Entidades.Mantenimiento", b =>
                {
                    b.HasOne("HotelDeCabañas.Entidades.Cabaña", "Cabaña")
                        .WithMany()
                        .HasForeignKey("CabañaNroHabitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabaña");
                });
#pragma warning restore 612, 618
        }
    }
}
